### ISSUE TITLE
Two bugfixes

### ISSUE THREAD

**Issue by drhexgit** [MultiCoreNop/Logitech-G19-Linux-Daemon#2]
Got it to display an image on my G19 keyboard display, but had to first fix two things in logitech/g19.py:
In  rgb_to_uint16(r, g, b):
  `valueL = (gBits  << 5) | bBits `           should be:
 ` valueL = ((gBits & 7) << 5) | bBits `

in G19UsbController/__init__
`iface1 = config.interfaces[1][0] `    should be:
`iface1 = config.interfaces[0][1] `

**Comment by MultiCoreNop** [comment]
Interesting - maybe "something changed" over the years? Currently I do not have a G19 around to test this, so I'll add this to the readme for now.
Thanks!
